export interface NoteRanking {
    label: string,
    category: string,
    subCategory?: string,
    gloom: number,
    temp: number,
    fanciness: number,
    mood: number
}

const noteMasterList: NoteRanking[] = [
    {
        label: "Citrus",
        category: "perfume",
        temp: .15,
        fanciness: .7,
        gloom: .95,
        mood: .9
    }, {
        label: "Floral",
        category: "perfume",
        temp: .35,
        fanciness: .9,
        gloom: .7,
        mood: .55
    }, {
        label: "Fruity",
        category: "perfume",
        temp: .65,
        fanciness: .3,
        gloom: .75,
        mood: .85
    }, {
        label: "Sweet",
        category: "perfume",
        temp: .75,
        fanciness: .18,
        gloom: .55,
        mood: .88
    }, {
        label: "Woody",
        category: "perfume",
        temp: .65,
        fanciness: .5,
        gloom: .4,
        mood: .4
    }, {
        label: "Herbal",
        category: "perfume",
        temp: .40,
        fanciness: .55,
        gloom: .6,
        mood: .6
    }, {
        label: "Green",
        category: "perfume",
        temp: .35,
        fanciness: .6,
        gloom: .8,
        mood: .48
    }, {
        label: "Gourmand",
        category: "perfume",
        temp: .85,
        fanciness: .45,
        gloom: .48,
        mood: .9
    }, {
        label: "Amber",
        category: "perfume",
        temp: .75,
        fanciness: .55,
        gloom: .45,
        mood: .45
    }, {
        label: "Aquatic",
        category: "perfume",
        temp: .05,
        fanciness: .65,
        gloom: .5,
        mood: .5
    }, {
        label: "Chemical",
        category: "perfume",
        temp: .5,
        fanciness: .35,
        gloom: .7,
        mood: .45
    }, {
        label: "Dry",
        category: "perfume",
        temp: .45,
        fanciness: .5,
        gloom: .6,
        mood: .45
    }, {
        label: "Musk",
        category: "perfume",
        temp: .7,
        fanciness: .38,
        gloom: .5,
        mood: .5
    }, {
        label: "Light",
        category: "perfume",
        temp: .1,
        fanciness: .65,
        gloom: .9,
        mood: .52
    }, {
        label: "Dark",
        category: "perfume",
        temp: .8,
        fanciness: .5,
        gloom: .35,
        mood: .35
    }, {
        label: "Soft",
        category: "perfume",
        temp: .48,
        fanciness: .53,
        gloom: .75,
        mood: .55
    }, {
        label: "Heavy",
        category: "perfume",
        temp: .85,
        fanciness: .4,
        gloom: .4,
        mood: .45
    }, {
        label: "Bright",
        category: "perfume",
        temp: .2,
        fanciness: .6,
        gloom: .95,
        mood: .58
    }, {
        label: "Summer",
        category: "perfume",
        temp: .4,
        fanciness: .5,
        gloom: .65,
        mood: .65
    }, {
        label: "Winter",
        category: "perfume",
        temp: .7,
        fanciness: .45,
        gloom: .48,
        mood: .6
    }, {
        label: "Spring",
        category: "perfume",
        temp: .35,
        fanciness: .55,
        gloom: .78,
        mood: .58
    }, {
        label: "Fall",
        category: "perfume",
        temp: .7,
        fanciness: .4,
        gloom: .35,
        mood: .6
    }, {
        label: "Masculine",
        category: "perfume",
        temp: .6,
        fanciness: .55,
        gloom: .35,
        mood: .4
    }, {
        label: "Feminine",
        category: "perfume",
        temp: .4,
        fanciness: .65,
        gloom: .6,
        mood: .58
    }, {
        label: "Unisex",
        category: "perfume",
        temp: .55,
        fanciness: .4,
        gloom: .45,
        mood: .52
    }, {
        label: "Happy",
        category: "mood",
        temp: .65,
        fanciness: .3,
        gloom: 1,
        mood: 1
    }, {
        label: "Playful",
        category: "mood",
        subCategory: "Happy",
        temp: .55,
        fanciness: .25,
        gloom: 1,
        mood: .95
    }, {
        label: "Proud",
        category: "mood",
        subCategory: "Happy",
        temp: .45,
        fanciness: .7,
        gloom: .7,
        mood: .7
    }, {
        label: "Creative",
        category: "mood",
        subCategory: "Happy",
        temp: .5,
        fanciness: .25,
        gloom: .45,
        mood: .8
    }, {
        label: "Confident",
        category: "mood",
        subCategory: "Happy",
        temp: .8,
        fanciness: .6,
        gloom: .4,
        mood: .9
    }, {
        label: "Hopeful",
        category: "mood",
        subCategory: "Happy",
        temp: .65,
        fanciness: .5,
        gloom: .8,
        mood: .75
    }, {
        label: "Excited",
        category: "mood",
        subCategory: "Happy",
        temp: .8,
        fanciness: .45,
        gloom: .9,
        mood: .85
    }, {
        label: "Sad",
        category: "mood",
        temp: .3,
        fanciness: .65,
        gloom: .15,
        mood: .3
    }, {
        label: "Lonely",
        category: "mood",
        subCategory: "Sad",
        temp: .2,
        fanciness: .45,
        gloom: 0,
        mood: .15
    }, {
        label: "Hurt",
        category: "mood",
        subCategory: "Sad",
        temp: .45,
        fanciness: .35,
        gloom: 0,
        mood: .4
    }, {
        label: "Fragile",
        category: "mood",
        subCategory: "Sad",
        temp: 0,
        fanciness: .8,
        gloom: .15,
        mood: .45
    }, {
        label: "Embarassed",
        category: "mood",
        subCategory: "Sad",
        temp: .6,
        fanciness: .5,
        gloom: .5,
        mood: .35
    }, {
        label: "Angry",
        category: "mood",
        temp: .9,
        fanciness: .25,
        gloom: .55,
        mood: .35
    }, {
        label: "Frustrated",
        category: "mood",
        subCategory: "Angry",
        temp: .85,
        fanciness: .35,
        gloom: .35,
        mood: .45
    }, {
        label: "Numb",
        category: "mood",
        subCategory: "Angry",
        temp: 0,
        fanciness: .8,
        gloom: .1,
        mood: .1
    }, {
        label: "Disgusted",
        category: "mood",
        subCategory: "Angry",
        temp: .55,
        fanciness: .65,
        gloom: .45,
        mood: .3
    }, {
        label: "Disappointed",
        category: "mood",
        subCategory: "Angry",
        temp: .45,
        fanciness: .3,
        gloom: .35,
        mood: .4
    }, {
        label: "Anxious",
        category: "mood",
        temp: .4,
        fanciness: .35,
        gloom: .65,
        mood: .45
    }, {
        label: "Fearful",
        category: "mood",
        subCategory: "Anxious",
        temp: .4,
        fanciness: .65,
        gloom: .2,
        mood: .35
    }, {
        label: "Overwhelmed",
        category: "mood",
        subCategory: "Anxious",
        temp: .65,
        fanciness: .45,
        gloom: .2,
        mood: .5
    }, {
        label: "Tired",
        category: "mood",
        temp: .35,
        fanciness: .65,
        gloom: .35,
        mood: .45
    }, {
        label: "Bored",
        category: "mood",
        subCategory: "Tired",
        temp: .5,
        fanciness: .45,
        gloom: .45,
        mood: .5
    }, {
        label: "Stressed",
        category: "mood",
        subCategory: "Tired",
        temp: .6,
        fanciness: .65,
        gloom: .45,
        mood: .3
    }, {
        label: "Confused",
        category: "mood",
        subCategory: "Tired",
        temp: .4,
        fanciness: .6,
        gloom: .5,
        mood: .5
    }
]

export default noteMasterList;